#!/bin/sh

set -x

_PID=$(pgrep -x awesome)
_UID=$(ps -o uid= -p $_PID)
USER=$(id -nu $_UID)
DBUS_ADDRESS_VAR=$(cat /proc/$_PID/environ | grep -z "^DBUS_SESSION_BUS_ADDRESS=" | xargs -0 echo)

notify() {
  	su - $USER -c "/bin/bash \
                    -c ' \
                        export DISPLAY=:0; \
                        export XAUTHORITY='/home/$USER/.Xauthority'; \
                        export $DBUS_ADDRESS_VAR; \
                        dbus-send --dest=org.awesomewm.awful --type=method_call \
                          / org.awesomewm.awful.Remote.Eval string:"updateScreens\\\(\\\"$1\\\"\\\)" \
                    ' \
                "
    }

logger "notify-awesome: " "$@"
notify $1
