#!/bin/bash

set -e
set -o pipefail

if [[ "$1" == "-d" ]]
then
	cat $2 | grep "@@.*@@" | sed 's^.*@@\(.*\)@@.*^\1^' | sort | ( uniq || true) | sed 's@^\(.*\)$@.local/share/passwords/\1.gpg@' | xargs echo "$3: "
else
	tempdir="$(mktemp -d)"
	trap "rm -rf $tempdir" EXIT
	cat > $tempdir/buffer
	cp $tempdir/buffer $tempdir/working
	cat $tempdir/buffer | (grep "@@.*@@" || true) | sed 's^.*@@\(.*\)@@.*^\1^' | sort | uniq | while read f
	do
		sed s^@@$f@@^$(gpgcat .local/share/passwords/$f.gpg)^g -i $tempdir/working
	done
	cat $tempdir/working
fi
